@base_url = http://localhost:8080/api/my-locations

### get locations for that user only 
GET {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE2NjE1Nn0.B5lr14bOgI1lfn6UD1A3RYYAyz_gTDzBVcP2gzShOOQ

### get by zipcode
GET {{base_url}}/19107 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE2NTkxM30.Y2mbB7dGxcHSsN2yA28MhzwEa5QMiFsIGYnQM1TBXng

### add new location

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE2NjE1Nn0.B5lr14bOgI1lfn6UD1A3RYYAyz_gTDzBVcP2gzShOOQ

{
    "city": "Philadelphia",
    "state": "PA",
    "zipCode": 19122
}

### delete

DELETE {{base_url}}/19107 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE2NjE1Nn0.B5lr14bOgI1lfn6UD1A3RYYAyz_gTDzBVcP2gzShOOQ