@base_url = http://localhost:8080/api/my-locations

### get locations for that user only 
GET {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNjE5MTA3NX0.CI081d82vYkx_Q9r8aNXx0jlpwg75MxtcrywHhza0QI

### get by zipcode
GET {{base_url}}/28278 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE3NzY5OX0.eJECGIYJzPhqcQeV8oM8ZZ8EYFY8wdnen_Pvt_ugIww

### add new location

POST {{base_url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNjE5MDc2MX0.4VnTBE6ZFfgzQ5crTtNmgiitIbb-3aNfUIZtTfcmDSk

{
    "city": "Philadelphia",
    "state": "PA",
    "zipCode": 19107
}

### delete

DELETE {{base_url}}/19107 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ0Y3NsaWJyYXJ5Iiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IkFETUlOIiwiYXBwX3VzZXJfaWQiOjEsImV4cCI6MTcwNTE3NzY5OX0.eJECGIYJzPhqcQeV8oM8ZZ8EYFY8wdnen_Pvt_ugIww